app.mail.environment-name=test
app.mail.mail-server-url=http://localhost:8080/test-mail-server
app.mail.support-email=test-support@javaguides.com
app.mail.send-real-emails=false
app.mail.welcome-subject=Welcome from Test Employee Management System