app.mail.environment-name=dev
app.mail.mail-server-url=http://localhost:8080/dev-mail-server
app.mail.support-email=dev-support@javaguides.com
app.mail.send-real-emails=false
app.mail.welcome-subject=Welcome from Dev Employee Management System